#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import importlib
from genpy.message import strify_message

import sys
import rospy
from ros_wild.subscriber import EchoSubscriber


def callback(msg, topic_name):
    echo_msg = """---
topic: {}

{}
""".format(topic_name, strify_message(msg))
    sys.stdout.write(echo_msg)


def echo(topic_name, message_type):
    rospy.init_node("ros_wild_topic", anonymous=True)
    try:
        package, class_name = message_type.split("/", 1)
        module = importlib.import_module("{}.msg".format(package))
        msg_class = getattr(module, class_name)
    except ImportError:
        rospy.logerr("Unknown message type: {}".format(message_type))
        return
    else:
        EchoSubscriber(topic_name, msg_class, callback)
        rospy.spin()


def main():
    parser = argparse.ArgumentParser(description='ros_wild echo')
    parser.add_argument("topic_name", type=str,
                        help="Regular expression of topic name to subscribe.")
    parser.add_argument("message_type", type=str,
                        help="Type of topic to subscribe. ex) std_msgs/String")
    args = parser.parse_args()
    echo(args.topic_name, args.message_type)

if __name__ == '__main__':
    main()
